name: "FUXA"
description: "Easy and Web-based Process Visualization (SCADA/HMI/Dashboard) software - now for Home Assistant"
url: "https://github.com/8OND007/FUXA-HA/"
image: "frangoteam/fuxa"
version: "1.2.6"
slug: "fuxa"
webui: "http://[HOST]:[PORT:1881]/home"
environment:
  LOG_LEVEL: "info"
options: {}
schema: {}
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: addon_config   # /Share under HA Samba map "addon_configs"
    read_only: False
    path: /usr/src/app/FUXA/server/_appdata
  - type: share   # /Share under HA Samba map "share"
    read_only: False
    path: /usr/src/app/FUXA/server/_db
  - type: media   # /Share under HA Samba map "media"
    read_only: False
    path: /usr/src/app/FUXA/server/_images
  - type: share   # /Share under HA Samba map "share"
    read_only: False
    path: /usr/src/app/FUXA/server/_logs
startup: services
ports:
  1881/tcp: 1881
