name: "FUXA-HA"
description: "Easy and Web-based Process Visualization (SCADA/HMI/Dashboard) software - now for Home Assistant"
version: "1.0.0"
url: "https://github.com/8OND007/FUXA-HA/"
slug: "fuxa-slr"
webui: "http://[HOST]:[PORT:1881]/home"
panel_icon: mdi:dog
panel_title: FUXA
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - /usr/src/app/FUXA/server/_appdata:share:rw
  - addons:rw
  - config:rw
startup: services
ports:
  1881/tcp: 1881
ingress: true
ingress_port: 1881
