name: "FUXA by SmartLiving.Rocks"
description: "Web-based Process Visualization (SCADA/HMI/Dashboard) software"
version: "1.0.0"
url: "https://github.com/SmartLiving-Rocks/FUXA/"
slug: "fuxa-slr"
ingress: true
ingress_port: 1881
ingress_stream: false
panel_icon: mdi:dog
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  1881/tcp: 1881
