name: "FUXA by SmartLiving.Rocks"
description: "My second real add-on!"
version: "1.0.0"
slug: "Web-based Process Visualization (SCADA/HMI/Dashboard) software"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  1881/tcp: 1881
